apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: orderflow
  labels:
    tier: api
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: api
  template:
    metadata:
      labels:
        tier: api
    spec:
      containers:
        - name: nginxdemos
          image: nginxdemos/hello
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: api-config
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
